### ISSUE TITLE
First architecture diagram

### ISSUE THREAD

**Issue by unlanza** [unlanza/object-storage#1]
## Background 🌎
Working towards a first implementation of the solution it's important to know what's going to be built.

## Objective 🎯
Define and document the architecture for the first version of the issue.

### 📋 Requirements 
- Use `C#` as main language for solution.
- Consider AWS as the main development and production environment.

## Tasks 📌
- [ ] Read [The Google File System Whitepaper - paper.dvi (mit.edu)](https://pdos.csail.mit.edu/6.824/papers/gfs.pdf).
- [ ] Define solution diagram.
- [ ] Add to documentation.

## References 🔗
- [How does a distributed file system like Google GFS work? (youtube.com)](https://www.youtube.com/watch?v=x6k-ndoWn7U&t=557s)
- [Let's rewrite Google File System in Rust! Rust Distributed File System RDFS: Project setup (youtube.com)](https://www.youtube.com/watch?v=gTtGy3bQTPk&t=31s)

**Comment by unlanza** [comment]
Here's one reference more: 
>[S3 Architecture - by Neo Kim - System Design Newsletter](https://newsletter.systemdesign.one/p/s3-architecture)

**Comment by unlanza** [comment]
Here's another one:
> [The infinite canvas SDK • tldraw](https://tldraw.dev/)
